### PR TITLE
Pipeline test

### PR DESCRIPTION
**Pull request by denanmusinovic**
Everything is finised and working beside directory  listing, but from what i understand that is not possible on nginx side since it's only used as proxy, it has to be implemented on nodejs side.

### CODE REVIEW

**Comment by bararchy** [comment]
@gmesserman , @amar771 WDYT? regarding directly listing

**Comment by amar771** [comment]
as far as I know it's possible to do that on nginx side? 
https://stackoverflow.com/questions/10663248/how-to-configure-nginx-to-enable-kinda-file-browser-mode
https://www.keycdn.com/support/nginx-directory-index

**Comment by gmesserman** [comment]
> @gmesserman , @amar771 WDYT? regarding directly listing

Directory listing works on nginx (e.g. - https://nl-bc.dev.sogoservices.com/vendor/), it just needs to be configured carefully so it will not conflict with /* mapping for client. The original nginx config (default.conf) that we committed and is being used by our docker-compose does include the correct configuration, so you can either use it directly or adjust your nginx.conf accordingly. 

I am also attaching here the config with working directory listing in this comment.

[nginx.txt](https://github.com/NeuraLegion/brokencrystals/files/5757270/nginx.txt)

**Comment by denanmusinovic** [comment]
Yes when nginx is serving files directly, in our case its just a proxy for
nodejs.

**Comment by gmesserman** [comment]
The relevant lines in file are -
       location / {
            autoindex on;       	   
            try_files $uri $uri/ /index.html =404;
        }

Also, if you are using different nginx config, make sure you have a proper mapping for put.raw 

        location /put.raw {
            rewrite put.raw /api/file/raw?path=./gil.txt break;
            proxy_pass http://nodejs:3000;
        }

**Comment by gmesserman** [comment]
> Yes when nginx is serving files directly, in our case its just a proxy for

Please take a look at the original nginx config. The nginx serves static files and only proxies the API calls to node.

**Comment by gmesserman** [comment]
docker-compose does - 
1. generates new nodejs docker with server app
2. starts nginx standard docker and mounts volume for config and for static content

**Pull request closed without merging**
