### PR TITLE
fix(default.conf): enable access to public files

### PR DESCRIPTION
**Pull request by bararchy**
Add the files for the common files from #236

### CODE REVIEW

**Comment by rielas** [comment]
@gasRU76 Could you visually check if this nginx config is valid 🙏?

**Review by derevnjuk — COMMENTED** [review]
@bararchy What about other files like .htaccess and .env? 

Also, please adjust the PR title and body according to the contributing guide)

**Comment by bararchy** [comment]
@derevnjuk `.env` is here: https://github.com/NeuraLegion/brokencrystals/pull/237/files#diff-399f9a2b27955861f6d655786beb8e1657617616f6b9cc66318fb0cc255617b8R34 

About HTACCESS...Actually I don't know? let me check if we are aiming to see it somewhere

**Comment by bararchy** [comment]
@derevnjuk added .htaccess and fixed the PR title. 

This doesn't have an NLJ ticket or any automation at NLDS so I don't think using smart commits or some special structure is needed.

**Review by derevnjuk — APPROVED** [review]

**Comment by derevnjuk** [comment]
> This doesn't have an NLJ ticket or any automation at NLDS so I don't think using smart commits or some special structure is needed.

However, as stated in the contribution guidelines, the PR body should contain not a list of the changes, but an explanation of their purpose of them 😄

**Pull request merged**
