### PR TITLE
Adding Auto-build file

### PR DESCRIPTION
**Pull request by danizz91**
Create new auto-build file that run npm build and npm test.

### CODE REVIEW

**Review by rielas — APPROVED** [review]

**Comment by rielas** [comment]
@bararchy
@danizz91 created a CI for broken crystals. It might help us

**Comment by bararchy** [comment]
Looks good but seems to be failing XD

**Comment by rielas** [comment]
But @danizz91 can't fix the tests themselves

**Comment by bararchy** [comment]
ofc, we need to see priority to get those passing.

**Comment by bararchy** [comment]
@derevnjuk do you want those in?

**Comment by derevnjuk** [comment]
@bararchy @rielas there are only dummy tests here. You can remove `npm run test` line at all

**Pull request closed without merging**
